providers:
  # Dynamic file config
  file:
    directory: /etc/traefik/conf
    watch: true
  # Docker configuration backend
  docker:
    exposedByDefault: false
    defaultRule: {}

log:
  level: DEBUG

api:
  insecure: true

entryPoints:
  websecure:
    address: ":443"